### PR TITLE
windows: fix winusb_get_device_string failing for strict USB devices

### LINKED ISSUE #1794: New libusb_get_device_string function does not work for all devices
I saw that the upcomming libusb 1.0.30 got some new functions for accessing the device strings without opening the device. I have tried the new `libusb_get_device_string` function with the listdevs example, and it reports correct strings for some, but not all devices. The old `libusb_get_string_descriptor` does work for all devices.

The devices which don’t work include a USB headset and one of our own devices. The libusb debug output shows:

> libusb: error [winusb_get_device_string] could not access string descriptor 1 for 'USB\VID_1395&PID_00B0\5&1FEFB85F&0&10': [31] Ein an das System angeschlossenes Gerõt funktioniert nicht.

I’ve also attached the USB Tree View Output for this device. Tested on Windows 10 with libusb 1.0.30 rc1. Any idea why the new function does not work with all devices?

[UsbTreeView_report.txt](https://github.com/user-attachments/files/26566222/UsbTreeView_report.txt)

### PR DESCRIPTION
**Pull request by sonatique**
[EDITED for description of the third issue]
Three bugs in winusb_get_device_string caused libusb_get_device_string
to return empty strings instead of actual device strings on Windows:

1. The function used wIndex=0 (invalid LANGID) when requesting string
   descriptors via IOCTL_USB_GET_DESCRIPTOR_FROM_NODE_CONNECTION. While
   some devices tolerate LANGID 0, strict USB devices correctly STALL
   the request (Windows error 31). Fix: first fetch string descriptor 0
   to get the device's language table (USB 2.0 section 9.6.7), then use
   the primary LANGID for actual string requests. The LANGID is cached
   per device to avoid redundant IOCTLs.

2. On IOCTL failure, the function returned 0 instead of a negative
   LIBUSB_ERROR code. The caller in libusb_get_device_string only
   checks for rv < 0, so 0 was treated as success: an empty string
   was permanently cached, and subsequent calls returned 1 (empty
   string + null terminator) without ever retrying. Fix: return
   LIBUSB_ERROR_IO on both error paths.

3. When a device has no string descriptor of a given type
   (descriptor index is 0 in the device descriptor), the function
   returned 0 instead of an error. This caused an empty string to be
   cached and returned as success, while Linux and Darwin return an
   error in the same situation. Fix: return LIBUSB_ERROR_NOT_FOUND
   for consistency with other backends (using Darwing value which seemed
   more precise than Linux.

Closes #1794

### CODE REVIEW

**Comment by tormodvolden** [comment]
I thought libusb_get_device_string() would not create I/O and use cached values from the OS, but here I see a DeviceIoControl() call. Does this call create I/O? Or is libusb_get_device_string() not I/O free on Windows anyway?

**Comment by mcuee** [comment]
> I thought libusb_get_device_string() would not create I/O and use cached values from the OS, but here I see a DeviceIoControl() call. Does this call create I/O? Or is libusb_get_device_string() not I/O free on Windows anyway?

As per the comments in PR #1532, no better ways for Windows now.

From PR #1532.
https://github.com/libusb/libusb/pull/1532/changes#diff-bd7e9ed3e7d8a4a69d0664da0f6b8dbbff0b2c608d8dd63de02c379c98cf88b4R2201-R2222

```

/*
 * Backend implementation for libusb_get_device_string().
 * 
 * Windows makes getting the common device strings
 * very difficult.  DEVPKEY_Device_* does not have SerialNumber,
 * and it reports the driver manufacturer, not the device manufacturer.
 * 
 * We could parse the serial number from the DEVICE_ID string:
 * https://learn.microsoft.com/en-us/windows-hardware/drivers/install/device-instance-ids
 * https://learn.microsoft.com/en-us/windows-hardware/drivers/install/standard-usb-identifiers
 * 
 * However, using the dev_id for getting the serial number is 
 * definitely not recommended.
 *
 * The following implementation uses an IOCTL
 * to the parent USB hub to perform the USB control request for the
 * string descriptor without opening the USB device.
 * While we would rather not invoke USB IO, we currently lack a 
 * better option.
 */
static int winusb_get_device_string(libusb_device *dev,
	enum libusb_device_string_type string_type, char *data, int length)
{
```

**Comment by mcuee** [comment]
Not able to recreate the issues for Issue #1794, but at least no regressions now.

```
PS C:\work\libusb\libusb> .\build\v145\x64\Release-Hotplug-MT\testlibusb.exe
Dev (bus 2, device 12): 1EA7 - 0064 speed: 12M
  Product:                   2.4G Mouse
Dev (bus 2, device 11): 25A7 - FA61 speed: 12M
  Manufacturer:              Compx
  Product:                   2.4G Receiver
Dev (bus 2, device 9): 046D - C548 speed: 12M
  Manufacturer:              Logitech
  Product:                   USB Receiver
Dev (bus 1, device 7): 05E3 - 0747 speed: 5G
Dev (bus 2, device 3): 0408 - 4044 speed: 480M
  Manufacturer:              Quanta
  Product:                   ACER QHD User Facing
Dev (bus 2, device 10): 16C0 - 05DC speed: 1.5M
  Manufacturer:              www.fischl.de
  Product:                   USBasp
Dev (bus 2, device 4): 0BDA - 0129 speed: 480M
Dev (bus 2, device 1): 248A - 5B2F speed: 12M
  Manufacturer:              SSCYPL
  Product:                   Wireless-Receiver
Dev (bus 2, device 2): 1C7A - 0584 speed: 12M
Dev (bus 2, device 5): 8087 - 0036 speed: 12M
Dev (bus 2, device 7): 03EB - 2106 speed: 12M
  Manufacturer:              ATMEL
  Product:                   STK600
Dev (bus 1, device 6): 0BDA - 8156 speed: 5G
Dev (bus 1, device 5): 05E3 - 0625 speed: 10G
Dev (bus 2, device 8): 05E3 - 0610 speed: 480M
Dev (bus 2, device 0): 8086 - 7E7D speed: 10G
Dev (bus 1, device 0): 8086 - 7EC0 speed: 10G
Dev (bus 2, device 6): 05E3 - 0610 speed: 480M
Dev (bus 1, device 8): 05E3 - 0616 speed: 5G

PS C:\work\libusb\libusb> cd ..
PS C:\work\libusb> cd .\libusb_pr1796\

PS C:\work\libusb\libusb_pr1796> .\build\v145\x64\Release-Hotplug-MT\testlibusb.exe
Dev (bus 2, device 12): 1EA7 - 0064 speed: 12M
  Product:                   2.4G Mouse
Dev (bus 2, device 11): 25A7 - FA61 speed: 12M
  Manufacturer:              Compx
  Product:                   2.4G Receiver
Dev (bus 2, device 9): 046D - C548 speed: 12M
  Manufacturer:              Logitech
  Product:                   USB Receiver
Dev (bus 1, device 7): 05E3 - 0747 speed: 5G
Dev (bus 2, device 3): 0408 - 4044 speed: 480M
  Manufacturer:              Quanta
  Product:                   ACER QHD User Facing
Dev (bus 2, device 10): 16C0 - 05DC speed: 1.5M
  Manufacturer:              www.fischl.de
  Product:                   USBasp
Dev (bus 2, device 4): 0BDA - 0129 speed: 480M
Dev (bus 2, device 1): 248A - 5B2F speed: 12M
  Manufacturer:              SSCYPL
  Product:                   Wireless-Receiver
Dev (bus 2, device 2): 1C7A - 0584 speed: 12M
Dev (bus 2, device 5): 8087 - 0036 speed: 12M
Dev (bus 2, device 7): 03EB - 2106 speed: 12M
  Manufacturer:              ATMEL
  Product:                   STK600
Dev (bus 1, device 6): 0BDA - 8156 speed: 5G
Dev (bus 1, device 5): 05E3 - 0625 speed: 10G
Dev (bus 2, device 8): 05E3 - 0610 speed: 480M
Dev (bus 2, device 0): 8086 - 7E7D speed: 10G
Dev (bus 1, device 0): 8086 - 7EC0 speed: 10G
Dev (bus 2, device 6): 05E3 - 0610 speed: 480M
Dev (bus 1, device 8): 05E3 - 0616 speed: 5G
```

**Comment by mcuee** [comment]
Changing my Windows 11 system to Singapore Chinese -- still the same.

```
PS C:\work\libusb\libusb_pr1796> Get-Culture

LCID             Name             DisplayName
----             ----             -----------
4100             zh-SG            中文（新加坡）

PS C:\work\libusb\libusb_pr1796> .\build\v145\x64\Release-Hotplug-MT\testlibusb.exe
Dev (bus 2, device 12): 1EA7 - 0064 speed: 12M
  Product:                   2.4G Mouse
Dev (bus 2, device 11): 25A7 - FA61 speed: 12M
  Manufacturer:              Compx
  Product:                   2.4G Receiver
Dev (bus 2, device 9): 046D - C548 speed: 12M
  Manufacturer:              Logitech
  Product:                   USB Receiver
Dev (bus 1, device 7): 05E3 - 0747 speed: 5G
Dev (bus 2, device 3): 0408 - 4044 speed: 480M
  Manufacturer:              Quanta
  Product:                   ACER QHD User Facing
Dev (bus 2, device 10): 16C0 - 05DC speed: 1.5M
  Manufacturer:              www.fischl.de
  Product:                   USBasp
Dev (bus 2, device 4): 0BDA - 0129 speed: 480M
Dev (bus 2, device 1): 248A - 5B2F speed: 12M
  Manufacturer:              SSCYPL
  Product:                   Wireless-Receiver
Dev (bus 2, device 2): 1C7A - 0584 speed: 12M
Dev (bus 2, device 5): 8087 - 0036 speed: 12M
Dev (bus 2, device 7): 03EB - 2106 speed: 12M
  Manufacturer:              ATMEL
  Product:                   STK600
Dev (bus 1, device 6): 0BDA - 8156 speed: 5G
Dev (bus 1, device 5): 05E3 - 0625 speed: 10G
Dev (bus 2, device 8): 05E3 - 0610 speed: 480M
Dev (bus 2, device 0): 8086 - 7E7D speed: 10G
Dev (bus 1, device 0): 8086 - 7EC0 speed: 10G
Dev (bus 2, device 6): 05E3 - 0610 speed: 480M
Dev (bus 1, device 8): 05E3 - 0616 speed: 5G

PS C:\work\libusb\libusb_pr1796> cd ..

PS C:\work\libusb> cd libusb

PS C:\work\libusb\libusb> .\build\v145\x64\Release-Hotplug-MT\testlibusb.exe
Dev (bus 2, device 12): 1EA7 - 0064 speed: 12M
  Product:                   2.4G Mouse
Dev (bus 2, device 11): 25A7 - FA61 speed: 12M
  Manufacturer:              Compx
  Product:                   2.4G Receiver
Dev (bus 2, device 9): 046D - C548 speed: 12M
  Manufacturer:              Logitech
  Product:                   USB Receiver
Dev (bus 1, device 7): 05E3 - 0747 speed: 5G
Dev (bus 2, device 3): 0408 - 4044 speed: 480M
  Manufacturer:              Quanta
  Product:                   ACER QHD User Facing
Dev (bus 2, device 10): 16C0 - 05DC speed: 1.5M
  Manufacturer:              www.fischl.de
  Product:                   USBasp
Dev (bus 2, device 4): 0BDA - 0129 speed: 480M
Dev (bus 2, device 1): 248A - 5B2F speed: 12M
  Manufacturer:              SSCYPL
  Product:                   Wireless-Receiver
Dev (bus 2, device 2): 1C7A - 0584 speed: 12M
Dev (bus 2, device 5): 8087 - 0036 speed: 12M
Dev (bus 2, device 7): 03EB - 2106 speed: 12M
  Manufacturer:              ATMEL
  Product:                   STK600
Dev (bus 1, device 6): 0BDA - 8156 speed: 5G
Dev (bus 1, device 5): 05E3 - 0625 speed: 10G
Dev (bus 2, device 8): 05E3 - 0610 speed: 480M
Dev (bus 2, device 0): 8086 - 7E7D speed: 10G
Dev (bus 1, device 0): 8086 - 7EC0 speed: 10G
Dev (bus 2, device 6): 05E3 - 0610 speed: 480M
Dev (bus 1, device 8): 05E3 - 0616 speed: 5G
```

**Comment by mcuee** [comment]
BTW, another interesting finding.

For thebuilt-in USB devices of the Acer Swift Go 14 laptop (2024 model) like the WebCAM, USBview and USBTreeView will not be able to get the string descriptors since they are in Low Power mode. 

But all the different versions of libusb testlibusb example will be able to get the string descriptors. Looks like libusb Windows will wake up the device and get the string descriptors. I have tested libusb git, this PR, 1.0.29 release and 1.0.28 release.

```
Dev (bus 2, device 3): 0408 - 4044 speed: 480M
  Manufacturer:              Quanta
  Product:                   ACER QHD User Facing
```

**Comment by mcuee** [comment]
I will check the behavior of the dual boot Ubuntu 26.04 beta version as well tomorrow.

File: libusb/os/windows_winusb.c [hunk 1]
```diff
@@ -2260,13 +2260,45 @@ static int winusb_get_device_string(libusb_device *dev,
...
+	// String descriptor 0 with wIndex=0 returns the supported language table
+	// (USB 2.0 spec section 9.6.7). We use the first (primary) LANGID for
+	// all subsequent string descriptor requests.
+	if (0 == priv->langid) {
+		size = sizeof(sd);
+		memset(&sd, 0, size);
+		sd.req.ConnectionIndex = (ULONG)dev->port_number;
+		sd.req.SetupPacket.bmRequest = LIBUSB_ENDPOINT_IN;
+		sd.req.SetupPacket.bRequest = LIBUSB_REQUEST_GET_DESCRIPTOR;
+		sd.req.SetupPacket.wValue = (LIBUSB_DT_STRING << 8) | 0;
```
Comment (seanm) [inline libusb/os/windows_winusb.c]: `| 0`? Is that a typo?

**Comment by tormodvolden** [comment]
> As per the comments in PR #1532, no better ways for Windows now.
> 
> From PR #1532. https://github.com/libusb/libusb/pull/1532/changes#diff-bd7e9ed3e7d8a4a69d0664da0f6b8dbbff0b2c608d8dd63de02c379c98cf88b4R2201-R2222

Thanks for the pointer! At least it should work without opening the device (which on Windows means opening an interface).

File: libusb/os/windows_winusb.c (hunk 1 above)
Comment (tormodvolden) [reply libusb/os/windows_winusb.c]: I believe this is just a notation to clarify that whatever goes in the LSB is 0, to follow a pattern of a << 8 | b.

Comment (sonatique) [reply libusb/os/windows_winusb.c]: Indeed: Writing (LIBUSB_DT_STRING << 8) | 0 makes the structure explicit: we're requesting string descriptor index 0 (the language table).
But it is a matter of preference, we may remove it if this is more confusing than self-explaining.
or maybe I can add: /* index 0 = language table */

**Comment by sonatique** [comment]
@smarvonohr @mcuee @seanm @tormodvolden @Fishi96 : I think I am doing too many things at the same time: I totally forgot we had #1790 pending (and even that I had commented it) when I saw #1794 which was open afterward, and since @mcuee requested my help, I jumped into it and didn't make the connection immediately. I thus try to solve #1794 on my own, resulting in this PR.

And now, when browsing recent PRs because something looked familiar after all, I realized some of the issues were already fixed by #1790, so I could have built upon it rather than creating a whole new PR, this may look a bit rude, sorry.

Anyway, now that we are in this situation, I compared both PR, and found that, in my opinion this one is actually going a little bit further in solving the problems of #1790:

- both first extract LANGID, which is good
- #1790 does not cache LANGID, resulting in 2x IOCTLs x3 strings so additional 6x IOCTLs per device. This PR cache the result. We may like of not the idea of caching because it adds a struct member, but I prefer it over multiple IOCTLs
- #1790 falls back to langId = 0 in case of validation failure, which reproduce the original broken behavior. This PR return LIBUSB_ERROR_IO, which seems the more correct error value to me.

So for these reason I would recommend merging this one and unfortunately dropping #1790, but I am open to any other solution.

**Comment by sonatique** [comment]
Note: amended my commit to fix this: https://github.com/libusb/libusb/issues/1794#issuecomment-4217884739

**Comment by mcuee** [comment]
> So for these reason I would recommend merging this one and unfortunately dropping https://github.com/libusb/libusb/pull/1790, but I am open to any other solution.

I agree.

**Comment by mcuee** [comment]
As Issue #1794 is a regression, I have added #1794 and #1796 to milestone 1.0.30.

**Comment by smarvonohr** [comment]
Looks good to me.

**Review by mcuee — APPROVED** [review]

File: libusb/os/windows_winusb.c (hunk 1 above)
Comment (tormodvolden) [reply libusb/os/windows_winusb.c]: Adding that `index 0 = language table` comment would be nice.

Comment (sonatique) [reply libusb/os/windows_winusb.c]: I did it

**Review by seanm — APPROVED** [review]
